---
title: "BioSensIA-DC"
format: 
   gfm:
      toc: true
      toc-depth: 4
lang: en
engine: knitr
execute: 
  echo: true
  eval: false
  warning: true
  error: true
  include: true

---
  
## Welcome to the repository for the **BioSensIA-DC prototype**

This is work in progress.


## What BioSensIA-DC is

This repository contains the code for BioSensIA-DC, the software prototype for project BioSensIA.

BioSensIA-DC is based on [DrugCLIP](https://github.com/bowen-gao/DrugCLIP), which in turn uses [Uni-Mol](https://github.com/deepmodeling/Uni-Mol/tree/main/unimol). More information about those projects can be found in [the DrugCLIP paper](https://arxiv.org/pdf/2310.06367.pdf) and in [the Uni-Mol paper](https://openreview.net/forum?id=6K2RM6wVqKu).


## System requirements

We have run BioSensIA-DC on GNU-Linux only. If you have been able to run it on other operating systems, [please let us know](https://github.com/fnaufel/BioSensIA-DC/issues/new/choose).

The software dependencies of BioSensIA are described below.


## How to install BioSensIA-DC

### Install `uv`

[`uv`](https://docs.astral.sh/uv/) is a modern and efficient package and environment manager for Python. Please refer to their website for [instructions on how to install it](https://docs.astral.sh/uv/getting-started/installation/) for your system.


### Check your CUDA driver

1. Make sure your GPU is available --- for example, if you use [Slurm](https://slurm.schedmd.com/overview.html) on an HPC cluster, open a shell on a GPU node with the following command:

   ```{bash}
   srun --partition=gpu --gres=gpu:1 --time=00:05:00 --pty bash
   ```

1. Run the [`nvcc` command](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html):

   ```{bash}
   nvcc --version
   ```

   The output will be something like
   
   ```
   nvcc: NVIDIA (R) Cuda compiler driver
   Copyright (c) 2005-2024 NVIDIA Corporation
   Built on Tue_Feb_27_16:19:38_PST_2024
   Cuda compilation tools, release 12.4, V12.4.99
   Build cuda_12.4.r12.4/compiler.33961263_0
   ```
   
   This says we have release 12.4.


### Clone this repo

Go to a directory of your choice and run

```{bash}
git clone https://github.com/fnaufel/BioSensIA-DC.git
```

or download a [zip file of the master branch](https://github.com/fnaufel/BioSensIA-DC/archive/refs/heads/master.zip) and unzip it.

Then go to the project's directory:

```{bash}
cd BioSensIA-DC
```


### Edit `pyproject.toml` to set correct values for your system

Open [`pyproject.toml`](pyproject.toml) in a text editor. You will see these lines at the end of the file:

```toml
[tool.uv.sources]
torch = [
  { index = "pytorch-cu124", marker = "sys_platform == 'linux'" },
]
torchvision = [
  { index = "pytorch-cu124", marker = "sys_platform == 'linux'" },
]
torchaudio = [
  { index = "pytorch-cu124", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true
```

1. If necessary, change `cu124` to `cuxxx`, where `xxx` is the release of your CUDA driver.

1. If necessary, change `linux` to your operating system (e.g., `win32`).

1. **Do not** change anything else in this file, unless you know what you are doing.

For more details, see the [uv page about installing PyTorch](https://docs.astral.sh/uv/guides/integration/pytorch/).


### Use `uv` to install the dependencies

```{bash}
uv sync
```


### Activate the virtual environment

```{bash}
source .venv/bin/activate
```


### Confirm everything is ok so far

#### Python version

1. Run

   ```{bash}
   which python
   ```
   
   The output should end with `BioSensIA-DC/.venv/bin/python`

1. Run

   ```{bash}
   python --version
   ```
   
   The output should be of the form
   
   ```
   Python 3.11.xx
   ```
   
   where `xx` varies according to the [patch version](https://semver.org) installed.


#### PyTorch with GPU access

1. Make sure your GPU is available --- for example, if you use [Slurm](https://slurm.schedmd.com/overview.html) on an HPC cluster, open a shell on a GPU node with the following command:

   ```{bash}
   srun --partition=gpu --gres=gpu:1 --time=00:05:00 --pty bash
   ```

1. Run the following in your shell:

   ```{bash}
   python - << PY
   import os
   import torch
   
   x = torch.rand(5, 3)
   print(x)
   print("torch.__version__                   =", torch.__version__)
   print("torch.version.cuda                  =", torch.version.cuda)
   print("torch.backends.cuda.is_built        =", torch.backends.cuda.is_built())
   print("torch.cuda.is_available             =", torch.cuda.is_available())
   print("torch.cuda.device_count             =", torch.cuda.device_count())
   
   if torch.cuda.is_available():
     print("device 0 name                       =", torch.cuda.get_device_name(0))
   print("torch.distributed.is_nccl_available =", torch.distributed.is_nccl_available())
   PY
   ```

   The output should be something like

   ```
   tensor([[0.4314, 0.7784, 0.5975],
           [0.5675, 0.0199, 0.3430],
           [0.9700, 0.3156, 0.9717],
           [0.1576, 0.8838, 0.7823],
           [0.1090, 0.2737, 0.9940]])
   torch.__version__                   = 2.6.0+cu124
   torch.version.cuda                  = 12.4
   torch.backends.cuda.is_built        = True
   torch.cuda.is_available             = True
   torch.cuda.device_count             = 1
   device 0 name                       = NVIDIA A2
   torch.distributed.is_nccl_available = True
   ```


#### RDKit

Run

```{bash}
python - <<'PY'
from rdkit import Chem
from rdkit.Chem import Descriptors
print("RDKit version:", Chem.rdBase.rdkitVersion)
mol = Chem.MolFromSmiles("CCO")
print("Canonical SMILES:", Chem.MolToSmiles(mol))
print("Num atoms:", mol.GetNumAtoms())
print("Molecular weight:", Descriptors.MolWt(mol))
PY
```

The output should be

```
RDKit version: 2022.09.5
Canonical SMILES: CCO
Num atoms: 3
Molecular weight: 46.069
```


### Install Uni-Core

[Uni-Core](https://github.com/dptech-corp/Uni-Core) is a distributed PyTorch framework on which BioSensIA-DC depends.

It must be built from source (with a build option to enable CUDA extensions) and manually overlaid into the virtual environment.

The [Uni-Core source](external/Uni-Core) is included in the BioSensIA-DC repo. 

Make sure the virtual environment is activated:

```{bash}
source .venv/bin/activate
```

Change to the appropriate directory:

```{bash}
cd ./external/Uni-Core/
```

Build with

```{bash}
python setup.py install --enable-cuda-ext
```

```{=markdown}
> [!CAUTION] 
> As Uni-Core has been built from source (and not installed
> via `uv`), it is not formally included in the list of dependencies in
> `pyproject.toml`.
>
> This means that running `uv sync` after this point **will remove it**
> from the environment.
>
> To avoid this, **if you need to synchronize the environment, use**
>
> ```bash
> uv sync --inexact
> ```
>
> instead. This will preserve packages installed by means other than
> `uv`.
```


### Confirm Uni-Core install is ok

To confirm the `unicore-train` script has been installed in the right place:

```{bash}
which unicore-train
```

The output should end with `BioSensIA-DC/.venv/bin/unicore-train`.

The Uni-Core repository has [instructions on how to train a BERT model](external/Uni-Core/examples/bert/example_data/README.md) in order to confirm Uni-Core is working.

The instructions tell you to download and preprocess the data, but **that is not necessary, as we have already included all the preprocessed files in this repository**.

To start training the BERT model:

1. Make sure your GPU is available --- for example, if you use Slurm on an HPC cluster, open a shell on a GPU node with the following command:

   ```{bash}
   srun --partition=gpu --gres=gpu:2 --pty bash
   ```

1. Run the script:

   ```{bash}
   cd ./external/Uni-Core/examples/bert
   ./train_bert_test.sh
   ```

To check whether Uni-Core is using the GPU(s), look for something like this in the output of `train_bert_test.sh`:

```
2026-04-20 11:17:29 | INFO | unicore_cli.train | training on 2 devices (GPUs)
```


### Download and install DrugCLIP data 

The [DrugCLIP README](external/DrugCLIP/README.md) says that train data, the trained checkpoint and the test data for DUD-E can be found at  <https://drive.google.com/drive/folders/1zW1MGpgunynFxTKXC2Q4RgWxZmg6CInV>.

You should download the files (use [gdown](https://github.com/wkentaro/gdown), for example), uncompress them and organize them like so:

```
BioSensIA-DC/external/DrugCLIP
                      ├── data/
                      │   ├── DUD-E/
                      │   │   └── raw/
                      │   │       └── all/
                      │   │           └── ...
                      │   ├── emb/
                      │   ├── lit_pcba/
                      │   │   └── ...
                      │   ├── pdb/
                      │   ├── train.lmdb
                      │   ├── valid.lmdb
                      │   ├── dict_mol.txt
                      │   └── dict_pkt.txt
                      ├── mols.lmdb
                      ├── pocket.lmdb
                      ├── checkpoint_best.pt
                      ├── mol_pre_no_h_220816.pt
                      ├── pocket_pre_220816.pt
                      └── ...
```

The files `train.lmdb` and `valid.lmdb` exist in two archives: `pdbbind_only.zip` and `train_no_test_af.zip`. Use the latter.


### Make the script files executable

If necessary:

```{bash}
cd ./external/DrugCLIP
chmod a+x *.sh
```


## How to use BioSensIA-DC

### How to run the original DrugCLIP

#### Benchmarks

The bash script [`external/DrugCLIP/test.sh`](external/DrugCLIP/test.sh) runs the tests on the PCBA or the DUD-E benchmarks. To choose which, you must edit the script file. Assign the desired dataset to the `TASK` variable:

```{bash}
TASK="PCBA" # DUDE or PCBA
```

Then run

```{bash}
cd ./external/DrugCLIP
./test.sh
```

Because of hard-coded constraints in the original DrugCLIP code, a GPU must be available for the script to run.

A good sanity check is to compare the values output by these runs to the values reported in Sections 4.1 and 4.2 of the [DrugCLIP paper](https://arxiv.org/pdf/2310.06367.pdf).


#### Retrieval (virtual screening)

The DrugCLIP code in the original repository will only do **virtual screening**: you can submit a query consisting of one or more pockets, and the system will produce a list of molecules ranked according to (the maximum of) their compatibility with the pockets.

The default list of candidate molecules is contained in `external/DrugCLIP/mols.lmdb`. 

The list of query pockets must be contained in a file whose path is the value of the `POCKET_PATH` variable in the script.

The directory `external/DrugCLIP/data/pdb/combine_set/` contains binding data of 
a total of 23496 biomolecular complexes, including protein-ligand (19443), 
nucleic acid-ligand (149), protein-nucleic acid (1052), and protein-protein 
complexes (2852). See `external/DrugCLIP/data/pdb/combine_set/readme/PDBbind-101.txt` for more details.

We have implemented a Python function to search this data and produce an LMDB file containing the pockets specified in the arguments. See the definition of the `create_pocket_lmdb` function in [`biosensia_retrieval.py`](biosensia_retrieval.py) for more details.

For example, the following code creates the file `query_pocket.lmdb` containing information for the enzyme PP2A in a complex with okadaic acid:

```{python}
import biosensia_retrieval as retr
retr.create_pocket_lmdb('2ie4', 'query_pocket.lmdb')
```

After the definition of the query pocket(s), retrieval is done by executing the shell script [`external/DrugCLIP/retrieval.sh`](external/DrugCLIP/retrieval.sh). Read the comments in that file to see how to configure it.

```{bash}
cd ./external/DrugCLIP
./retrieval.sh
```

The first time the retrieval script is run, DrugCLIP must generate embeddings for **all** of the candidate molecules. This may take a long time. The generated embeddings are saved to a file in the directory specified by the `EMB_DIR` variable. Subsequent runs with the same set of candidate molecules will be much faster, as they will use these saved embeddings.

The ranked list of molecules will be saved in a TSV file named `ranked_compounds.txt`, located in the same directory as the saved embeddings. Each line of the file will contain the SMILES formula of the molecule and its score (the maximum value of its compatibility with any pocket in the query).

Because of hard-coded constraints in the original DrugCLIP code, a GPU must be available for the script to run.


### How to do target fishing

The code in the original DrugCLIP repository does not support target fishing (submitting query **molecules** to retrieve **pockets** ranked by their compatibility with the query molecules). We have implemented this functionality.


#### Build the LMDB file containing the candidate pockets

Because the code in the original DrugCLIP repository did not handle target fishing, there is no candidate-pocket LMDB for the molecule-to-pocket direction. BioSensIA builds one from the exact pocket records in `external/DrugCLIP/data/train.lmdb` and `external/DrugCLIP/data/valid.lmdb`, preserving duplicate raw PDB IDs because repeated training records can have distinct pocket geometries. To build this file, run

```{python}
import biosensia_target_fishing as tf
tf.build_candidate_pockets_lmdb()
```

The default is to save the file as `data/candidate_pockets.lmdb`. If you rebuild or replace this file, remove the corresponding pocket embedding cache before benchmarking; the cache filename is based on the LMDB basename and checkpoint, not on the LMDB contents.

See the definition of the `build_candidate_pockets_lmdb` function in [`biosensia_target_fishing.py`](biosensia_target_fishing.py) for more details.


#### Build the LMDB file containing the query molecule(s)

The list of query molecules must be contained in the LMDB file passed as `--mol-path` to the target-fishing command. If you use the compatibility shell wrapper, this is the `MOL_PATH` variable in [`target_fishing.sh`](external/DrugCLIP/target_fishing.sh).

You can get the query molecules from the file `external/DrugCLIP/mols.lmdb`, which contains information about 2,942,719 molecules; however, the records in that file can only be searched **sequentially**. To speed things up, you must run the function `build_mol_lmdb_index`, in [`biosensia_target_fishing.py`](biosensia_target_fishing.py), to build an index file. In Python, run

```{python}
import biosensia_target_fishing as tf
tf.build_mol_lmdb_index()
```

Building the molecule index takes a long time, but it only needs to be done once.

After the molecule index has been built, you can invoke the function `create_mol_lmdb` to save an LMDB file containing the molecule(s) you want to submit as a query. You can specify the molecule(s) in any of the following ways (you may pass a single string or a list of strings):

- SMILES strings are supported directly. Use raw strings (`r'...'`) to keep `\` from being interpreted as an escape character.
- DrugCLIP IDs are matched against the local source LMDB (default `external/DrugCLIP/mols.lmdb`).
- PubChem CIDs like `"cid:2244"` or `"2244"` and PubChem compound names are searched in [PubChem](https://pubchem.ncbi.nlm.nih.gov).

If you pass the SMILES formula for a molecule that is not in the local source LMDB, it is resolved through PubChem when the argument `download_missing` is true (the default).

For example, all of the calls below save an LMDB file named `data/oka.lmdb` containing the exact same information about **okadaic acid** as the query molecule:

```{python}
import biosensia_target_fishing as tf

# SMILES
smi = (
   r'C[C@@H]1CC[C@]2(CCCCO2)O[C@@H]1[C@@H](C)C[C@@H]([C@@H]3C(=C)[C@H]' +
   r'([C@H]4[C@H](O3)CC[C@]5(O4)CC[C@@H](O5)/C=C/[C@@H](C)' +
   r'[C@@H]6CC(=C[C@@]7(O6)[C@@H](CC[C@H](O7)C[C@](C)(C(=O)O)O)O)C)O)O'
)
tf.create_mol_lmdb(smi, 'data/oka.lmdb')

# Pubchem CID or compound name
tf.create_mol_lmdb('CID: 446512', 'data/oka.lmdb')
tf.create_mol_lmdb('446512', 'data/oka.lmdb')
tf.create_mol_lmdb('okadaic acid', 'data/oka.lmdb')
```

Okadaic acid is **not** in the local source LMDB file, so all of these calls resort to downloading data from PubChem.

See the definition of the `create_mol_lmdb` function in [`biosensia_target_fishing.py`](biosensia_target_fishing.py) for more details.


#### Run the search

The target-fishing Python entry point is [`biosensia_target_fishing.py`](biosensia_target_fishing.py). It runs DrugCLIP through the registered Uni-Core `drugclip` task, but paths are resolved from the BioSensIA-DC repository root.

```{bash}
python -m biosensia_target_fishing \
  --mol-path data/query_mol.lmdb \
  --pocket-path data/candidate_pockets.lmdb \
  --emb-dir external/DrugCLIP/data/pocket_emb \
  --top-k 1000
```

The shell script [`external/DrugCLIP/target_fishing.sh`](external/DrugCLIP/target_fishing.sh) is kept as a compatibility wrapper around this root-level Python module.

The first time the target fishing script is run, DrugCLIP must generate embeddings for **all** of the candidate pockets. This may take a long time. The generated embeddings are saved to a file in the directory specified by the `EMB_DIR` variable, whose default is `external/DrugCLIP/data/pocket_emb`. Subsequent runs with the same set of candidate pockets will be much faster, as they will use these saved embeddings.

The ranked list of pockets will be saved in a TSV file named `ranked_pockets.txt`, located in the same directory as the saved embeddings. Each line of the file will contain the candidate pocket identifier and its score (the maximum value of its compatibility with any molecule in the query).

Because of hard-coded constraints in the original DrugCLIP code, a GPU must be available for the script to run.


#### Build a positive-pair table for benchmarking

Target-fishing benchmarks use an explicit positive-pair table so the same runner can evaluate DrugCLIP validation data, CASF-2016, or other external datasets. For DrugCLIP validation data, this table can be derived directly from the validation LMDB:

```{python}
from biosensia_target_fishing_benchmark import write_positive_pairs_from_lmdb

write_positive_pairs_from_lmdb(
    "data/biosensia_finetune/valid.lmdb",
    "runs/target_fishing_benchmarks/valid_positives.parquet",
)
```


#### Benchmark BioSensIA-DC with `valid.lmdb`

The DrugCLIP/BioSensIA validation LMDB can be used as a target-fishing benchmark because each record contains one positive ligand-pocket pair. The benchmark still uses three explicit artifacts:

- a query molecule LMDB containing the validation ligands;
- a candidate pocket LMDB containing the pockets to rank;
- a positive-pair table mapping each query molecule to its known positive pocket(s).

Run the commands below from the BioSensIA-DC repository root. A CUDA-capable GPU is expected, because the DrugCLIP target-fishing encoder path moves inference batches to CUDA.

1. Build or refresh the candidate pocket LMDB. This copies the exact pocket geometries from `external/DrugCLIP/data/train.lmdb` and `external/DrugCLIP/data/valid.lmdb`, preserving duplicate candidate pockets.

```{python}
import biosensia_target_fishing as tf

tf.build_candidate_pockets_lmdb(
    output_path="data/candidate_pockets.lmdb",
    source_data_dir="external/DrugCLIP/data",
    splits=("train", "valid"),
)
```

If you rebuild `data/candidate_pockets.lmdb`, remove any old pocket embedding cache for that LMDB before benchmarking.

2. Build the positive-pair table from the validation LMDB.

```{python}
from biosensia_target_fishing_benchmark import write_positive_pairs_from_lmdb

write_positive_pairs_from_lmdb(
    "data/biosensia_finetune/valid.lmdb",
    "runs/target_fishing_benchmarks/valid_positives.parquet",
)
```

3. Build a query molecule LMDB from the validation LMDB. The query records only need the molecule-side fields used by DrugCLIP target fishing. Duplicate SMILES are collapsed so each query molecule is ranked once.

```{python}
from lmdb_helpers import read_lmdb_records, write_lmdb_records

valid_records = read_lmdb_records("data/biosensia_finetune/valid.lmdb")
query_records = []
seen_smiles = set()

for record in valid_records:
    smi = str(record["smi"])
    if smi in seen_smiles:
        continue
    seen_smiles.add(smi)
    query_records.append(
        {
            "atoms": record["atoms"],
            "coordinates": record["coordinates"],
            "smi": smi,
        }
    )

write_lmdb_records(
    query_records,
    "runs/target_fishing_benchmarks/valid_query_mols.lmdb",
    overwrite=True,
    map_size=1 << 40,
)
```

4. Run the benchmark for one fine-tuned checkpoint. Replace `RUN_NAME` with the run directory you want to evaluate under `runs/biosensia_finetune`.

```{bash}
RUN_NAME="projection_lr1e-4_tau071_lambda-mp5pm5_bs96_bsv48_uf1_ppl8"

python -m biosensia_target_fishing_benchmark \
  --positives-path runs/target_fishing_benchmarks/valid_positives.parquet \
  --mol-path runs/target_fishing_benchmarks/valid_query_mols.lmdb \
  --pocket-path data/candidate_pockets.lmdb \
  --checkpoint-path "runs/biosensia_finetune/${RUN_NAME}/checkpoints/checkpoint_best.pt" \
  --emb-dir "runs/target_fishing_benchmarks/pocket_emb/${RUN_NAME}" \
  --top-k 1000 \
  --metric-top-k 1,3,5,10 \
  --output "runs/target_fishing_benchmarks/${RUN_NAME}.json"
```

5. To benchmark every fine-tuned run that has a `checkpoint_best.pt`, use a shell loop:

```{bash}
for checkpoint in runs/biosensia_finetune/*/checkpoints/checkpoint_best.pt; do
  run_name="$(basename "$(dirname "$(dirname "$checkpoint")")")"
  python -m biosensia_target_fishing_benchmark \
    --positives-path runs/target_fishing_benchmarks/valid_positives.parquet \
    --mol-path runs/target_fishing_benchmarks/valid_query_mols.lmdb \
    --pocket-path data/candidate_pockets.lmdb \
    --checkpoint-path "$checkpoint" \
    --emb-dir "runs/target_fishing_benchmarks/pocket_emb/${run_name}" \
    --top-k 1000 \
    --metric-top-k 1,3,5,10 \
    --output "runs/target_fishing_benchmarks/${run_name}.json"
done
```

Each output JSON contains the checkpoint path, input artifact paths, retrieval depth, and ranking metrics such as MRR, top-k accuracy, and recall@k. Candidate pocket embeddings are cached under the `--emb-dir` path, so later runs of the same checkpoint and candidate LMDB are faster.


## Roadmap

- Solve [open issues](../../issues).
- Run target fishing benchmarks.
- Implement BioSensIA-DC GUI.
